### ISSUE TITLE
Boot ROM doesn't react to buttons

### ISSUE THREAD

**Issue by NieDzejkob** [Akatsuki-py/Worldwide#3]
When I run a DMG game and press an arrow during the boot animation to change the palette, the background of the animation doesn't change, and the ROM still plays with the classic green palette.

**Comment by Akatsuki-py** [comment]
> When I run a DMG game and press an arrow during the boot animation to change the palette, the background of the animation doesn't change, and the ROM still plays with the classic green palette.

Thank you for your issue. I'll remove the mock video of startup. Since this is an "emulator", I'm sorry to do something like this.

**Comment by Akatsuki-py** [comment]
I had removed mock video of startup and remove this feature from README.md
