### ISSUE TITLE
Inaccurate emulation: mooneye-gb tests

### ISSUE THREAD

**Issue by NieDzejkob** [Akatsuki-py/Worldwide#4]
Test ROMs source code: https://github.com/Gekkio/mooneye-gb/tree/master/tests/acceptance
Assembled package: https://gekkio.fi/files/mooneye-gb/latest/mooneye-gb_hwtests.zip

I have tried running, from the basic acceptance directory, the following tests:

- [x] `add_sp_e_timing`
- [x] `div_timing`
- [x] `call_cc_timing`
- [x] `jp_timing`
- [x] `push_timing`
- [x] `oam_dma/basic`
- [x] `oam_dma/reg_read`
- [x] `instr/daa.gb`
- [x] `ld_hl_sp_e_timing`
- [x] `intr_timing`
- [x] `oam_dma_restart`

The ones with the checkbox not marked have failed. `div_timing` seems to be testing something that some of the other tests implicitly rely on. I did not run the whole test suite as I was only interested in a rough accuracy metric.

**Comment by Akatsuki-py** [comment]
My emulator passed all 11 tests. So I close this issue. If possible, I'd like you to confirm it, @NieDzejkob !

**Comment by NieDzejkob** [comment]
I tried some other tests from the test suite and found some other failures:

- [ ] `call_cc_timing2`
- [ ] `call_timing2`
- [ ] `di_timing-GS.gb` (note: this test is expected to pass only when ran on a DMG or SGB, and fail when ran on a CGB or AGB. This is because the name ends in `-GS`, as explained [here](https://github.com/Gekkio/mooneye-gb#test-naming))
- [ ] `ei_sequence`
- [ ] `ei_timing`
- [ ] `halt_ime0_nointr_timing`
- [ ] `halt_ime1_timing2-GS` (`-GS`, so the note above also applies)
- [ ] `if_ie_registers`
- [ ] `interrupts/ie_push`
- [ ] `oam_dma/sources-GS` (this CRASHES the emulator itself)
- [ ] `oam_dma_start`
- [ ] `pop_timing`
- [ ] `ppu/hblank_ly_scx_timing-GS`
- [ ] `ppu/intr_1_2_timing-GS`
- [ ] `ppu/intr_2_0_timing`
- [ ] `ppu/intr_2_mode0_timing`
- [ ] `rapid_di_ei`
- [ ] `../manual-only/sprite_priority.gb` ([here's how it should look](https://raw.githubusercontent.com/Gekkio/mooneye-gb/master/tests/manual-only/sprite_priority-expected.png))
- [ ] probably some others I haven't ran

I would suggest something creating a short program that would
- Run your emulator on each test
- Save a screenshot
- Compare to expected, or to a hash of the pixels

This would mean you could easily catch regressions, where a test was passing and now doesn't.

**Comment by Akatsuki-py** [comment]
OK. As well as reopening this issue, I open an issue to run the test to make sure the test case and pixel match. I am very grateful for your issue.
